/*
1. 학생별 2009년도 평균 학점을 저장한 테이블 생성하기.
   (년도, 학번, 이름, 평균학점 컬럼 필요)

   2009년도에 대해서 각 학생마다의 평균학점을 구해야 한다.
   => GROUP BY 년도, 학번, 이름
*/

-- 테이블 생성과 동시에 데이터 추가
CREATE TABLE STD_AVG_POINT AS
SELECT SUBSTR(B.TERM_NO,1,4) AS 년도
        , B.STUDENT_NO AS 학번
        , A.STUDENT_NAME AS 이름
        , AVG(B.POINT) AS 학점
    FROM TB_STUDENT A JOIN TB_GRADE B
    ON A.STUDENT_NO = B.STUDENT_NO
    WHERE B.TERM_NO LIKE '2009%'
    GROUP BY SUBSTR(B.TERM_NO,1,4), B.STUDENT_NO, A.STUDENT_NAME;

DROP TABLE STD_AVG_POINT;

-- 기존 테이블 바탕으로 새로운 테이블 생성 CREATE 후에
-- 기존 테이블의 데이터를 생성한 테이블 구조에 맞추어 추가 INSERT : 서브쿼리 이용
CREATE TABLE STD_AVG_POINT(
      년도      VARCHAR2(10)    NOT NULL
    , 학번      VARCHAR2(10)    NOT NULL
    , 이름      VARCHAR2(10)    NOT NULL
    , 평균학점  NUMBER(3,2)
);
INSERT INTO STD_AVG_POINT(
    SELECT SUBSTR(B.TERM_NO,1,4)
         , A.STUDENT_NO
         , A.STUDENT_NAME
         , AVG(B.POINT)
      FROM TB_STUDENT A JOIN TB_GRADE B
        ON A.STUDENT_NO = B.STUDENT_NO
     WHERE B.TERM_NO LIKE '2009%'
     GROUP BY SUBSTR(B.TERM_NO,1,4), A.STUDENT_NO, A.STUDENT_NAME
);
DESC STD_AVG_POINT;



/*
2. 학과별 학생 인원수와 교수 인원수를 저장한 테이블 생성하기.
   (학과코드, 학과명, 학생 인원수, 교수 인원수 컬럼 필요)

   TB_DEPARTMENT, TB_STUDENT, TB_PROFESSOR 테이블 JOIN
*/
-- 테이블 생성과 동시에 데이터 추가
CREATE TABLE DEPT_CNT AS
SELECT A.DEPARTMENT_NO AS 학과번호
     , A.DEPARTMENT_NAME AS 학과명
     , COUNT(DISTINCT B.STUDENT_NO) AS 학생인원
     , COUNT(DISTINCT C.PROFESSOR_NO) AS 교수인원
  FROM TB_DEPARTMENT A JOIN TB_STUDENT B
    ON A.DEPARTMENT_NO = B.DEPARTMENT_NO
  JOIN TB_PROFESSOR C
    ON A.DEPARTMENT_NO = C.DEPARTMENT_NO
 GROUP BY A.DEPARTMENT_NO, A.DEPARTMENT_NAME
 ORDER BY 1;


-- 두 개의 테이블을 JOIN하고 하나의 테이블 별칭명으로 지정하여 또다른 테이블을 JOIN
SELECT C.DEPARTMENT_NO AS 학과코드
     , C.DEPARTMENT_NAME AS 학과명
     , C.학생인원
     , COUNT(D.PROFESSOR_NO) AS 교수인원
  FROM (SELECT A.DEPARTMENT_NO
             , A.DEPARTMENT_NAME
             , COUNT(B.STUDENT_NO) AS 학생인원
          FROM TB_DEPARTMENT A JOIN TB_STUDENT B
            ON A.DEPARTMENT_NO = B.DEPARTMENT_NO
         GROUP BY A.DEPARTMENT_NO, A.DEPARTMENT_NAME) C
  JOIN TB_PROFESSOR D
    ON C.DEPARTMENT_NO = D.DEPARTMENT_NO
 GROUP BY C.DEPARTMENT_NO, C.DEPARTMENT_NAME, C.학생인원
 ORDER BY 1;
-- 아래처럼 JOIN하는 경우 테이블C가 테이블A와 B에 대해 각각 JOIN하여 COUNT에 곱이 이루어진다.
-- COUNT 해야하는 컬럼에 대해 각각 DISTINCT(중복제거)를 하여 3개의 테이블을 JOIN한다.
SELECT A.DEPARTMENT_NO AS 학과번호
     , A.DEPARTMENT_NAME AS 학과명
     , COUNT(DISTINCT B.STUDENT_NO) AS 학생인원
     , COUNT(DISTINCT C.PROFESSOR_NO) AS 교수인원
  FROM TB_DEPARTMENT A JOIN TB_STUDENT B
    ON A.DEPARTMENT_NO = B.DEPARTMENT_NO
  JOIN TB_PROFESSOR C
    ON A.DEPARTMENT_NO = C.DEPARTMENT_NO
 GROUP BY A.DEPARTMENT_NO, A.DEPARTMENT_NAME
 ORDER BY 1;